Repository cmwall0605/cse112-sp22-group8, pull requests merged in 2022-05, with the labels that each got.

#39 Task page boostrap removal
  source/index.html
  source/main.css
Labels: task-1-bootstrap-removal

#44 Fixed Unit Testing for Timer
  __tests__/timer.test.js
  source/timer_page/timer.js
Labels: bug, Priority: High, testing

#80 Create is noob system
  source/components/header-comp/header-comp.js
  source/timer-page/timer.html
  source/timer-page/timer.js
  source/timer-page/tutorial.js
Labels: task-09-ui
